# This playbook install a dropbear ssh server
# (https://matt.ucc.asn.au/dropbear/dropbear.html).
#
# Copyright (c) 2013-2016 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install dropbear package
  dnf: pkg={{ item }}
       state=present 
  with_items:
    - dropbear

- name: enable switch to port 222
  template: src=files/dropbear-config.j2 
            dest=/etc/sysconfig/dropbear
            owner=root
            group=root
            mode=0644

- name: configure firewall, allow traffic to port 222
  firewalld: port=222/tcp
             permanent=true
             state=enabled

- name: start dropbear
  service: name=dropbear
           state=running
           enabled=yes
