# This playbook install the ngIRCd (http://ngircd.barton.de/) irc server.
#
# Copyright (c) 2013-2016 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install ngircd package
  dnf: pkg={{ item }}
       state=present 
  with_items:
    - ngircd

- name: default ngircd configuration file
  template: src=files/ngircd.j2
            dest=/etc/ngircd.conf
            owner=root
            group=root
            mode=0644

- name: configure firewall, allow traffic to port 6667
  firewalld: port=6667/tcp
             permanent=true
             state=enabled

- name: start ngircd
  service: name=ngircd
           state=running
           enabled=yes
