# This playbook install the xrdp (http://www.xrdp.org/) RDP server.
#
# Copyright (c) 2013-2016 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install xrdp package
  dnf: pkg={{ item }}
       state=present 
  with_items:
    - xrdp

- name: configure firewall, allow traffic to 3389
  firewalld: port=3389/tcp
             permanent=true
             state=enabled

- name: start xrdp
  service: name=xrdp
           state=running
           enabled=yes
