# This playbook contains tasks to perform on a fresh Fedora installation to
# create a Fedora Security Lab Test bench. 
#
# Copyright (c) 2013-2016 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
# Usage: sudo ansible-playbook all-in-one.yml -f 10
# 
---
- hosts: fsl-tb
  user: root
  vars_files:
    - variables/application-versions.yml
    - variables/sensitive.yml
    - variables/containers.yml

  tasks:
# Common tasks
################################################################################
    - include: tasks/preparation.yml
    - include: tasks/motd.yml

# FSL Test bench specific stuff
################################################################################
    - include: tasks/web-servers/lighttpd.yml
    - include: tasks/web-interface.yml

# Services
################################################################################
## Web servers
    - include: tasks/web-servers/tomcat.yml
    - include: tasks/misc-servers/cups.yml
    - include: tasks/misc-servers/xrdp.yml
    - include: tasks/misc-servers/ntp.yml
    - include: tasks/misc-servers/mosquitto.yml
    - include: tasks/misc-servers/snmp.yml

# Helpers
################################################################################
    - include: tasks/helpers/linfo.yml

# Common Gateway Interface (CGI)
################################################################################
    - include: tasks/cgi/cgi.yml
    - include: tasks/cgi/time.yml
    - include: tasks/cgi/time-py.yml
    - include: tasks/cgi/env-sh.yml
    - include: tasks/cgi/system-sh.yml
    - include: tasks/cgi/time-pl.yml

# Vulnerable Web Application
################################################################################
    - include: tasks/apps/mcir.yml

# Shells
################################################################################
    - include: tasks/shells/b374k.yml
    - include: tasks/shells/dnashell.yml
    - include: tasks/shells/phpshell.yml

# Common tasks
################################################################################
#    - include: tasks/cleanup.yml

  handlers:
   - include: handlers/system.yml
   - include: handlers/services.yml
