# This playbook copy the ssh key to the managed node.
#
# Copyright (c) 2013-2019 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: copy the ssh key to the test bench
  command: /usr/bin/ssh-copy-id -i /root/.ssh/id_rsa.pub root@{{ ip }}
