# This playbook install the Linux Container aka LXC tools 
# (http://lxc.sourceforge.net/).
#
# Copyright (c) 2013-2019 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install the needed packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - lxc
    - libvirt-daemon-lxc
    - libvirt-daemon-driver-lxc
    - libvirt-daemon-config-network
    - virt-install

- name: start libvirtd
  service:
    name: libvirtd
    state: running
    enabled: yes
