# This playbook install the nginx webserver (http://nginx.org).
#
# Copyright (c) 2013-2016 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install nginx package
  dnf: pkg={{ item }}
       state=present 
  with_items:
    - nginx

#- name: run nginx on 8088
#  lineinfile: dest=/etc/nginx/nginx.conf
#              regexp='^        listen       80;'
#              insertafter='^        listen       80;'
#              line='        listen       8088;'
#              state=present

- name: create the certificate
  command: /usr/bin/openssl req -new -x509 -subj "/C={{ cert_country }}/ST={{ cert_province }}/L={{ cert_city }}/O={{ cert_org }}/CN={{ cert_cn }}/Email={{ cert_email }}" -days 3650 -keyout /etc/nginx/cert.key -out /etc/nginx/cert.pem -nodes

- name: create signing request
  command: /usr/bin/openssl req -new -subj "/C={{ cert_country }}/ST={{ cert_province }}/L={{ cert_city }}/O={{ cert_org }}/CN={{ cert_cn }}/Email={{ cert_email }}" -days 3650 -keyout /etc/nginx/tb.key -out /etc/nginx/tb.csr -nodes

- name: copy configuration file
  template: src=files/nginx-conf.j2 
            dest=/etc/nginx/nginx.conf
            owner=root
            group=root
            mode=0644

- name: configure firewall, allow traffic to port 8088
  firewalld: port=8088/tcp
             permanent=true
             state=enabled

- name: configure firewall, allow traffic to port 443
  firewalld: port=443/tcp
             permanent=true
             state=enabled

#- name: remove nginx default file
#  file: path=/usr/share/nginx/html/{{ item }}
#        state=absent
#  with_items:
#    - index.html
#    - nginx-logo.png
#    - poweredby.png
#    - 404.html
#    - 50x.html

- name: install a default index.html file
  template: src=files/web-interface/default.j2 
            dest=/usr/share/nginx/html/index.html
            owner=root
            group=root
            mode=0644
